bigquery_chess:
  outputs:
    test:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE') }}"
      project: chessgames
      dataset: test
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
    prod:
      type: bigquery
      method: service-account
      keyfile: "{{ env_var('GCP_SERVICE_ACCOUNT_KEYFILE') }}"
      project: chessgames
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
  target: "{{ env_var('BIGQUERY_DATASET') }}"
