bigquery_chess:
  outputs:
    dev:
      type: bigquery
      method: service-account
      keyfile: C:\Users\ZainSiddiqi\Downloads\chessgames-7ea1be9e813b.json
      project: chessgames
      dataset: test
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
    prod:
      type: bigquery
      method: service-account
      keyfile: C:\Users\ZainSiddiqi\Downloads\chessgames-7ea1be9e813b.json
      project: chessgames
      dataset: prod
      job_execution_timeout_seconds: 300
      job_retries: 1
      priority: interactive
      threads: 4
  target: prod
